### ISSUE TITLE
0.3 Roadmap

### ISSUE THREAD

**Issue by builder-247** [slothpixel/skyblock-parser#18]
This issue lists currently missing features that are now possible after https://github.com/HypixelDatabase/HypixelTracking/commit/c2ee0fbb417d52af6de10deb490d3ac7fefd2644

### Features
- [ ] Social skill
- [ ] Catacombs support
- [ ] Missing pets and pet items from Crystal Hollows
   - For reference: https://github.com/SkyCryptWebsite/SkyCrypt/blob/master/src/constants/pet-stats.js
- [ ] Pristine stat
- [ ] HotM stats & other mining stats
- [ ] Melody's Harp stats
- [ ] Potion effects
